{% set name = "liburcu" %}
{% set version = "0.14.0" %}

package:
  name: liburcu
  version: {{ version }}

source:
  url: https://lttng.org/files/urcu/userspace-rcu-{{ version }}.tar.bz2
  sha256: ca43bf261d4d392cff20dfae440836603bf009fce24fdc9b2697d837a2239d4f

build:
  number: 0
  skip: true  # [osx or win]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -e $PREFIX/include/urcu/urcu-memb.h      # [unix]
    - test -e $PREFIX/include/urcu/urcu-qsbr.h      # [unix]
    - test -e $PREFIX/include/urcu/urcu-mb.h        # [unix]
    - test -e $PREFIX/include/urcu/urcu-signal.h    # [unix]
    - test -e $PREFIX/include/urcu/urcu-bp.h        # [unix]
    - test -e $PREFIX/lib/liburcu-memb.so           # [unix]
    - test -e $PREFIX/lib/liburcu-qsbr.so           # [unix]
    - test -e $PREFIX/lib/liburcu-mb.so             # [unix]
    - test -e $PREFIX/lib/liburcu-bp.so             # [unix]
    - test -e $PREFIX/lib/liburcu-mb.so             # [unix]
about:
  home: https://liburcu.org/
  license: LGPL-2.0-or-later
  license_file: LICENSE
  summary: liburcu is a LGPLv2.1 userspace RCU (read-copy-update) library
  description: |
    liburcu is a LGPLv2.1 userspace RCU (read-copy-update) library
  doc_url: https://liburcu.org/
  dev_url: https://github.com/urcu/userspace-rcu

extra:
  recipe-maintainers:
    - ZimmerA
